# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.0.0
    hooks:
    -   id: pydocstyle
        # Temporary exclude files in which are in charge of offline reporting
        exclude: |
            (?x)^(
                tests/*|
                robotframework_reportportal/result_visitor.py|
                robotframework_reportportal/post_report.py|
                robotframework_reportportal/time_visitor.py
            )
-   repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
    -   id: rst-linter
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.0
    hooks:
    -   id: flake8
        # Temporary exclude files in which are in charge of offline reporting
        exclude: |
            (?x)^(
                robotframework_reportportal/result_visitor.py|
                robotframework_reportportal/post_report.py|
                robotframework_reportportal/time_visitor.py
            )$
